Repository Spidfail/irc_server, pull requests merged in 2022-04, with the labels that each got.

#6 Add Command Function
  Channel.cpp
  Channel.hpp
  Irc.cpp
  Irc.hpp
  Server.cpp
  Server.hpp
  User.cpp
  User.hpp
Labels: architecture

#7 ADD Comment and last methode
  Irc.hpp
  User.hpp
Labels: architecture

#9 Drwuu
  LICENSE
  Makefile
  headers/commands/command.hpp
  headers/commands/invite.hpp
  headers/commands/kick.hpp
  headers/commands/mode.hpp
  headers/error/error.hpp
  headers/irc.hpp
  headers/parser/parser.hpp
  headers/server.hpp
  server_test/server_test.cpp
  sources/commands/command.cpp
  sources/commands/invite.cpp
  sources/commands/kick.cpp
  sources/commands/mode.cpp
  sources/error/error.cpp
  sources/parser/parser.cpp
  sources/parser/parser_tester.cpp
  sources/server.cpp
Labels: parsing

#10 Test/connection
  headers/proxy/Address.hpp
  headers/proxy/Event.hpp
  headers/proxy/Proxy.hpp
  headers/proxy/Socket.hpp
  sources/proxy/Address.cpp
  sources/proxy/Proxy.cpp
  sources/proxy/test_client.cpp
  sources/proxy/test_server.cpp
Labels: architecture, connexion

#15 Proxy/implementation
  .gitignore
  Makefile
  headers/proxy/Address.hpp
  headers/proxy/Event.hpp
  headers/proxy/Proxy.hpp
  headers/proxy/Socket.hpp
  main_server.cpp
  sources/proxy/Address.cpp
  sources/proxy/Event.cpp
  sources/proxy/Proxy.cpp
  sources/proxy/test_client.cpp
Labels: architecture, connexion

#23 Events/implementations
  headers/proxy/Event.hpp
  headers/proxy/Socket.hpp
  sources/proxy/Event.cpp
Labels: architecture, connexion

#24 Events/implementations
  Makefile
  headers/proxy/Event.hpp
  headers/proxy/Proxy.hpp
  headers/proxy/Proxy_queue.hpp
  headers/proxy/Server_queue.hpp
  headers/proxy/Socket_event.hpp
  headers/structure/Server.hpp
  main_server.cpp
  sources/proxy/Event.cpp
  sources/proxy/Proxy.cpp
  sources/proxy/Proxy_queue.cpp
  sources/proxy/Server_queue.cpp
  sources/proxy/Socket_event.cpp
  sources/structure/User.cpp
Labels: architecture, connexion

#26 [LITTLEFIX] Erase unecessary classes + little Event
  .gitignore
  headers/proxy/Proxy.hpp
  headers/proxy/Server_queue.hpp
  sources/proxy/Proxy.cpp
  sources/proxy/Server_queue.cpp
Labels: architecture, connexion
